// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/auction.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BidResponse_Outcome int32

const (
	BidResponse_SUCCESS   BidResponse_Outcome = 0
	BidResponse_FAIL      BidResponse_Outcome = 1
	BidResponse_EXCEPTION BidResponse_Outcome = 2
)

// Enum value maps for BidResponse_Outcome.
var (
	BidResponse_Outcome_name = map[int32]string{
		0: "SUCCESS",
		1: "FAIL",
		2: "EXCEPTION",
	}
	BidResponse_Outcome_value = map[string]int32{
		"SUCCESS":   0,
		"FAIL":      1,
		"EXCEPTION": 2,
	}
)

func (x BidResponse_Outcome) Enum() *BidResponse_Outcome {
	p := new(BidResponse_Outcome)
	*p = x
	return p
}

func (x BidResponse_Outcome) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BidResponse_Outcome) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_auction_proto_enumTypes[0].Descriptor()
}

func (BidResponse_Outcome) Type() protoreflect.EnumType {
	return &file_proto_auction_proto_enumTypes[0]
}

func (x BidResponse_Outcome) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BidResponse_Outcome.Descriptor instead.
func (BidResponse_Outcome) EnumDescriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{1, 0}
}

type BidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidderId      string                 `protobuf:"bytes,1,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidRequest) Reset() {
	*x = BidRequest{}
	mi := &file_proto_auction_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidRequest) ProtoMessage() {}

func (x *BidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidRequest.ProtoReflect.Descriptor instead.
func (*BidRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{0}
}

func (x *BidRequest) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *BidRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type BidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Outcome       BidResponse_Outcome    `protobuf:"varint,1,opt,name=outcome,proto3,enum=auction.BidResponse_Outcome" json:"outcome,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BidResponse) Reset() {
	*x = BidResponse{}
	mi := &file_proto_auction_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BidResponse) ProtoMessage() {}

func (x *BidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BidResponse.ProtoReflect.Descriptor instead.
func (*BidResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{1}
}

func (x *BidResponse) GetOutcome() BidResponse_Outcome {
	if x != nil {
		return x.Outcome
	}
	return BidResponse_SUCCESS
}

func (x *BidResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ResultRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultRequest) Reset() {
	*x = ResultRequest{}
	mi := &file_proto_auction_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultRequest) ProtoMessage() {}

func (x *ResultRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultRequest.ProtoReflect.Descriptor instead.
func (*ResultRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{2}
}

type ResultResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AuctionOver   bool                   `protobuf:"varint,1,opt,name=auction_over,json=auctionOver,proto3" json:"auction_over,omitempty"`
	Winner        string                 `protobuf:"bytes,2,opt,name=winner,proto3" json:"winner,omitempty"`
	WinningBid    int32                  `protobuf:"varint,3,opt,name=winning_bid,json=winningBid,proto3" json:"winning_bid,omitempty"`
	HighestBid    int32                  `protobuf:"varint,4,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	Message       string                 `protobuf:"bytes,5,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResultResponse) Reset() {
	*x = ResultResponse{}
	mi := &file_proto_auction_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResultResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResultResponse) ProtoMessage() {}

func (x *ResultResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResultResponse.ProtoReflect.Descriptor instead.
func (*ResultResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{3}
}

func (x *ResultResponse) GetAuctionOver() bool {
	if x != nil {
		return x.AuctionOver
	}
	return false
}

func (x *ResultResponse) GetWinner() string {
	if x != nil {
		return x.Winner
	}
	return ""
}

func (x *ResultResponse) GetWinningBid() int32 {
	if x != nil {
		return x.WinningBid
	}
	return 0
}

func (x *ResultResponse) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *ResultResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Internal node-to-node messages
type SyncStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStateRequest) Reset() {
	*x = SyncStateRequest{}
	mi := &file_proto_auction_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateRequest) ProtoMessage() {}

func (x *SyncStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateRequest.ProtoReflect.Descriptor instead.
func (*SyncStateRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{4}
}

func (x *SyncStateRequest) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

type SyncStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Bids          map[string]int32       `protobuf:"bytes,1,rep,name=bids,proto3" json:"bids,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	HighestBid    int32                  `protobuf:"varint,2,opt,name=highest_bid,json=highestBid,proto3" json:"highest_bid,omitempty"`
	HighestBidder string                 `protobuf:"bytes,3,opt,name=highest_bidder,json=highestBidder,proto3" json:"highest_bidder,omitempty"`
	StartTime     int64                  `protobuf:"varint,4,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncStateResponse) Reset() {
	*x = SyncStateResponse{}
	mi := &file_proto_auction_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStateResponse) ProtoMessage() {}

func (x *SyncStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStateResponse.ProtoReflect.Descriptor instead.
func (*SyncStateResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{5}
}

func (x *SyncStateResponse) GetBids() map[string]int32 {
	if x != nil {
		return x.Bids
	}
	return nil
}

func (x *SyncStateResponse) GetHighestBid() int32 {
	if x != nil {
		return x.HighestBid
	}
	return 0
}

func (x *SyncStateResponse) GetHighestBidder() string {
	if x != nil {
		return x.HighestBidder
	}
	return ""
}

func (x *SyncStateResponse) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type ReplicateBidRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BidderId      string                 `protobuf:"bytes,1,opt,name=bidder_id,json=bidderId,proto3" json:"bidder_id,omitempty"`
	Amount        int32                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	Timestamp     int64                  `protobuf:"varint,3,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateBidRequest) Reset() {
	*x = ReplicateBidRequest{}
	mi := &file_proto_auction_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateBidRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateBidRequest) ProtoMessage() {}

func (x *ReplicateBidRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateBidRequest.ProtoReflect.Descriptor instead.
func (*ReplicateBidRequest) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{6}
}

func (x *ReplicateBidRequest) GetBidderId() string {
	if x != nil {
		return x.BidderId
	}
	return ""
}

func (x *ReplicateBidRequest) GetAmount() int32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *ReplicateBidRequest) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

type ReplicateBidResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReplicateBidResponse) Reset() {
	*x = ReplicateBidResponse{}
	mi := &file_proto_auction_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplicateBidResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplicateBidResponse) ProtoMessage() {}

func (x *ReplicateBidResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_auction_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplicateBidResponse.ProtoReflect.Descriptor instead.
func (*ReplicateBidResponse) Descriptor() ([]byte, []int) {
	return file_proto_auction_proto_rawDescGZIP(), []int{7}
}

func (x *ReplicateBidResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_proto_auction_proto protoreflect.FileDescriptor

const file_proto_auction_proto_rawDesc = "" +
	"\n" +
	"\x13proto/auction.proto\x12\aauction\"A\n" +
	"\n" +
	"BidRequest\x12\x1b\n" +
	"\tbidder_id\x18\x01 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\"\x90\x01\n" +
	"\vBidResponse\x126\n" +
	"\aoutcome\x18\x01 \x01(\x0e2\x1c.auction.BidResponse.OutcomeR\aoutcome\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"/\n" +
	"\aOutcome\x12\v\n" +
	"\aSUCCESS\x10\x00\x12\b\n" +
	"\x04FAIL\x10\x01\x12\r\n" +
	"\tEXCEPTION\x10\x02\"\x0f\n" +
	"\rResultRequest\"\xa7\x01\n" +
	"\x0eResultResponse\x12!\n" +
	"\fauction_over\x18\x01 \x01(\bR\vauctionOver\x12\x16\n" +
	"\x06winner\x18\x02 \x01(\tR\x06winner\x12\x1f\n" +
	"\vwinning_bid\x18\x03 \x01(\x05R\n" +
	"winningBid\x12\x1f\n" +
	"\vhighest_bid\x18\x04 \x01(\x05R\n" +
	"highestBid\x12\x18\n" +
	"\amessage\x18\x05 \x01(\tR\amessage\"+\n" +
	"\x10SyncStateRequest\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\x05R\x06nodeId\"\xed\x01\n" +
	"\x11SyncStateResponse\x128\n" +
	"\x04bids\x18\x01 \x03(\v2$.auction.SyncStateResponse.BidsEntryR\x04bids\x12\x1f\n" +
	"\vhighest_bid\x18\x02 \x01(\x05R\n" +
	"highestBid\x12%\n" +
	"\x0ehighest_bidder\x18\x03 \x01(\tR\rhighestBidder\x12\x1d\n" +
	"\n" +
	"start_time\x18\x04 \x01(\x03R\tstartTime\x1a7\n" +
	"\tBidsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x05R\x05value:\x028\x01\"h\n" +
	"\x13ReplicateBidRequest\x12\x1b\n" +
	"\tbidder_id\x18\x01 \x01(\tR\bbidderId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x05R\x06amount\x12\x1c\n" +
	"\ttimestamp\x18\x03 \x01(\x03R\ttimestamp\"0\n" +
	"\x14ReplicateBidResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2v\n" +
	"\aAuction\x120\n" +
	"\x03Bid\x12\x13.auction.BidRequest\x1a\x14.auction.BidResponse\x129\n" +
	"\x06Result\x12\x16.auction.ResultRequest\x1a\x17.auction.ResultResponse2\x9b\x01\n" +
	"\bNodeSync\x12B\n" +
	"\tSyncState\x12\x19.auction.SyncStateRequest\x1a\x1a.auction.SyncStateResponse\x12K\n" +
	"\fReplicateBid\x12\x1c.auction.ReplicateBidRequest\x1a\x1d.auction.ReplicateBidResponseB\x0fZ\rauction/protob\x06proto3"

var (
	file_proto_auction_proto_rawDescOnce sync.Once
	file_proto_auction_proto_rawDescData []byte
)

func file_proto_auction_proto_rawDescGZIP() []byte {
	file_proto_auction_proto_rawDescOnce.Do(func() {
		file_proto_auction_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)))
	})
	return file_proto_auction_proto_rawDescData
}

var file_proto_auction_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_auction_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_proto_auction_proto_goTypes = []any{
	(BidResponse_Outcome)(0),     // 0: auction.BidResponse.Outcome
	(*BidRequest)(nil),           // 1: auction.BidRequest
	(*BidResponse)(nil),          // 2: auction.BidResponse
	(*ResultRequest)(nil),        // 3: auction.ResultRequest
	(*ResultResponse)(nil),       // 4: auction.ResultResponse
	(*SyncStateRequest)(nil),     // 5: auction.SyncStateRequest
	(*SyncStateResponse)(nil),    // 6: auction.SyncStateResponse
	(*ReplicateBidRequest)(nil),  // 7: auction.ReplicateBidRequest
	(*ReplicateBidResponse)(nil), // 8: auction.ReplicateBidResponse
	nil,                          // 9: auction.SyncStateResponse.BidsEntry
}
var file_proto_auction_proto_depIdxs = []int32{
	0, // 0: auction.BidResponse.outcome:type_name -> auction.BidResponse.Outcome
	9, // 1: auction.SyncStateResponse.bids:type_name -> auction.SyncStateResponse.BidsEntry
	1, // 2: auction.Auction.Bid:input_type -> auction.BidRequest
	3, // 3: auction.Auction.Result:input_type -> auction.ResultRequest
	5, // 4: auction.NodeSync.SyncState:input_type -> auction.SyncStateRequest
	7, // 5: auction.NodeSync.ReplicateBid:input_type -> auction.ReplicateBidRequest
	2, // 6: auction.Auction.Bid:output_type -> auction.BidResponse
	4, // 7: auction.Auction.Result:output_type -> auction.ResultResponse
	6, // 8: auction.NodeSync.SyncState:output_type -> auction.SyncStateResponse
	8, // 9: auction.NodeSync.ReplicateBid:output_type -> auction.ReplicateBidResponse
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_proto_auction_proto_init() }
func file_proto_auction_proto_init() {
	if File_proto_auction_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_auction_proto_rawDesc), len(file_proto_auction_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_proto_auction_proto_goTypes,
		DependencyIndexes: file_proto_auction_proto_depIdxs,
		EnumInfos:         file_proto_auction_proto_enumTypes,
		MessageInfos:      file_proto_auction_proto_msgTypes,
	}.Build()
	File_proto_auction_proto = out.File
	file_proto_auction_proto_goTypes = nil
	file_proto_auction_proto_depIdxs = nil
}
